CREATE SCHEMA QA
GO

/* FUTURE PLACEHOLDER FOR METADATA QA PROCEDURE TO SCAN TABLE ACCESS, CHECK ALL FOUND METADATA TABLES AGAINST THE SYS.OBJECTS / SYS.COLUMNS TABLES FOR CORRECT DDL */
/* FUTURE PLACEHOLDER FOR METADATA QA PROCEDURE TO SCAN TABLE ACCESS, CHECK ALL FOUND METADATA TABLES FOR CORRECT INDEXES */
