/* ENACT QA view - QA_LOS
   v 0.1 - 20250331 - Darren W Henderson <darren.henderson@uky.edu>

   The following QA measures are calculated:
   LOS.0.1--NULL length of stay
   LOS.0.2--The site may be using NULL to represent 0 day length of stay
   LOS.0.3--LENGTH_OF_STAY differs from a calculated length of stay (based on START_DATE and END_DATE)
   LOS.0.4--LENGTH_OF_STAY differs from a calculated length of stay (based on START_DATE and END_DATE)
   LOS.0.5--START_DATE > END_DATE
   LOS.0.6--END_DATE is future dated

*/

CREATE OR ALTER VIEW QA.LENGTH_OF_STAY_VW AS
WITH CTE_LOS_QA AS (
SELECT 
    START_DATE
  , END_DATE
  , DATEDIFF(DD,START_DATE,END_DATE) CALC_LOS
  , LENGTH_OF_STAY
  , TRY_CAST(ABS(DATEDIFF(DD,START_DATE,END_DATE)-LENGTH_OF_STAY) AS BIT) AS CODED_DIFF
  , ABS(DATEDIFF(DD,START_DATE,END_DATE)-LENGTH_OF_STAY) AS CODED_DIFF_NUM_DAYS
  , IIF(DATEDIFF(DD,START_DATE,END_DATE)=0 AND LENGTH_OF_STAY IS NULL,1,0) NULL_AS_ZERO_LOS
  , NULL AS [MIN]
  , NULL AS [MAX]
FROM DBO.VISIT_DIMENSION
)
, CTE_QA_STATEMENTS AS (
SELECT 'LOS.0.1--NULL length of stay - Incidents:' AS QA_STATEMENT
  , SUM(CASE WHEN LENGTH_OF_STAY IS NULL THEN 1 ELSE 0 END) AS [MEAS_VALUE_1]
  , COUNT(*) AS [MEAS_VALUE_2]
  , FORMAT(1.0*SUM(CASE WHEN LENGTH_OF_STAY IS NULL THEN 1 ELSE 0 END)/COUNT(*), 'P3') AS PERC_TOTAL
  , NULL AS AVG_DIFFERENCE
  , NULL AS [MIN]
  , NULL AS [MAX]
  , TRY_CAST('DEFINITION: [MEAS_VALUE_1] = Number of records with a null length of stay in VISIT_DIMENSION.LENGTH_OF_STAY -- [MEAS_VALUE_2] = Number of records -- [PERC_TOTAL] = Percentage of VISIT_DIMENSION affected' AS VARCHAR(MAX)) AS COMMENT
FROM CTE_LOS_QA
UNION
SELECT 'LOS.0.2--The site may be using NULL to represent 0 day length of stay - Incidents:' AS QA_STATEMENT
  , SUM(NULL_AS_ZERO_LOS) AS [MEAS_VALUE_1]
  , COUNT(*) AS [MEAS_VALUE_2]
  , FORMAT(1.0*SUM(NULL_AS_ZERO_LOS)/COUNT(*), 'P3') AS PERC_TOTAL
  , NULL AS AVG_DIFFERENCE
  , NULL AS [MIN]
  , NULL AS [MAX]
  , TRY_CAST('DEFINITION: [MEAS_VALUE_1] = Number of records where START_DATE=END_DATE *AND* a null length of stay is present in VISIT_DIMENSION.LENGTH_OF_STAY -- [MEAS_VALUE_2] = Number of records -- [PERC_TOTAL] = Percentage of VISIT_DIMENSION affected' AS VARCHAR(MAX)) AS COMMENT
FROM CTE_LOS_QA
UNION
SELECT 'LOS.0.3--LENGTH_OF_STAY differs from a calculated length of stay (based on START_DATE and END_DATE) - Incidents:' AS QA_STATEMENT
  , SUM(CASE WHEN CODED_DIFF=1 THEN 1 ELSE 0 END) AS [MEAS_VALUE_1]
  , COUNT(*) AS [MEAS_VALUE_2]
  , FORMAT(1.0*SUM(CASE WHEN CODED_DIFF=1 THEN 1 ELSE 0 END)/COUNT(*), 'P3') AS PERC_TOTAL
  , NULL AS AVG_DIFFERENCE
  , NULL AS [MIN]
  , NULL AS [MAX]
  , TRY_CAST('DEFINITION: [MEAS_VALUE_1] = Number of records where the length of stay in VISIT_DIMENSION.LENGTH_OF_STAY does not agree with a datediff calculation between START_DATE AND END_DATE in VISIT_DIMENSION -- [MEAS_VALUE_2] = Number of records -- [PERC_TOTAL] = Percentage of VISIT_DIMENSION affected' AS VARCHAR(MAX)) AS COMMENT
FROM CTE_LOS_QA
UNION
SELECT 'LOS.0.4--LENGTH_OF_STAY differs from a calculated length of stay (based on START_DATE and END_DATE) - Total days:' AS QA_STATEMENT
  , SUM(CODED_DIFF_NUM_DAYS) AS [MEAS_VALUE_1]
  , SUM(CASE WHEN CODED_DIFF=1 THEN 1 ELSE 0 END) AS [MEAS_VALUE_2]
  , 'N/A' AS PERC_TOTAL
  , 1.0*SUM(CODED_DIFF_NUM_DAYS)/SUM(CASE WHEN CODED_DIFF=1 THEN 1 ELSE 0 END) AS AVG_DIFFERENCE
  , NULL AS [MIN]
  , NULL AS [MAX]
  , TRY_CAST('DEFINITION: [MEAS_VALUE_1] = Sum of total days (a measure of the impact of this error; this value is absolute) where the length of stay in VISIT_DIMENSION.LENGTH_OF_STAY does not agree with a datediff calculation between START_DATE AND END_DATE in VISIT_DIMENSION -- [MEAS_VALUE_2] = Number of records affected -- [PERC_TOTAL] = Not calculated -- [AVG_DIFFERENCE] = The average absolute difference between LENGTH_OF_STAY and DATEDIFF(DD,START_DATE,END_DATE)' AS VARCHAR(MAX)) AS COMMENT
FROM CTE_LOS_QA
UNION
SELECT 'LOS.0.5--START_DATE > END_DATE - Incidents:' AS QA_STATEMENT 
  , SUM(CASE WHEN START_DATE > END_DATE THEN 1 ELSE 0 END) AS [MEAS_VALUE_1]
  , COUNT(*) AS [MEAS_VALUE_2]
  , FORMAT(1.0*SUM(CASE WHEN START_DATE > END_DATE THEN 1 ELSE 0 END)/COUNT(*), 'P3') AS PERC_TOTAL
  , AVG(CASE WHEN START_DATE > END_DATE THEN (1.0*DATEDIFF(HH,END_DATE,START_DATE)) ELSE NULL END)/24 AS AVG_DIFFERENCE
  , TRY_CONVERT(VARCHAR(100),MIN(CASE WHEN START_DATE > END_DATE THEN START_DATE ELSE NULL END),120) AS [MIN] -- ISO8601 YYYY-MM-DD AS VARCHAR(100)
  , TRY_CONVERT(VARCHAR(100),MAX(CASE WHEN START_DATE > END_DATE THEN START_DATE ELSE NULL END),120) AS [MAX] -- ISO8601 YYYY-MM-DD AS VARCHAR(100)
  , TRY_CAST('DEFINITION: [MEAS_VALUE_1] = Number of records where VISIT_DIMENSION.START_DATE > VISIT_DIMENSION.END_DATE -- [MEAS_VALUE_2] = Number of records -- [PERC_TOTAL] = Percentage of VISIT_DIMENSION affected -- [AVG_DIFFERENCE] = The average number of days that START_DATE exceeds END_DATE (calculated in hours and divided by 24 for sub-day accuracy) -- [MIN] = When START_DATE exceeds END_DATE the MIN value of START_DATE found in the data -- [MAX] = When START_DATE exceeds END_DATE the MAX value of START_DATE found in the data' AS VARCHAR(MAX)) AS COMMENT
FROM CTE_LOS_QA
UNION
SELECT 'LOS.0.6--END_DATE is future dated - Incidents:' AS QA_STATEMENT 
  , SUM(CASE WHEN END_DATE > GETDATE() THEN 1 ELSE 0 END) AS [MEAS_VALUE_1]
  , COUNT(*) AS [MEAS_VALUE_2]
  , FORMAT(1.0*SUM(CASE WHEN END_DATE > GETDATE() THEN 1 ELSE 0 END)/COUNT(*), 'P3') AS PERC_TOTAL
  , AVG(CASE WHEN END_DATE > GETDATE() THEN DATEDIFF(HH,GETDATE(),END_DATE) ELSE NULL END)/24 AS AVG_DIFFERENCE
  , TRY_CONVERT(VARCHAR(100),MIN(CASE WHEN END_DATE > GETDATE() THEN END_DATE ELSE NULL END),120) AS [MIN] -- ISO8601 YYYY-MM-DD AS VARCHAR(100)
  , TRY_CONVERT(VARCHAR(100),MAX(CASE WHEN END_DATE > GETDATE() THEN END_DATE ELSE NULL END),120) AS [MAX] -- ISO8601 YYYY-MM-DD AS VARCHAR(100)
  , TRY_CAST('DEFINITION: [MEAS_VALUE_1] = Number of records where VISIT_DIMENSION.END_DATE > GETDATE() -- [MEAS_VALUE_2] = Number of records -- [PERC_TOTAL] = Percentage of VISIT_DIMENSION affected -- [AVG_DIFFERENCE] = The average number of days that END_DATE exceeds GETDATE() (calculated in hours and divided by 24 for sub-day accuracy) -- [MIN] = When END_DATE exceeds GETDATE() the MIN value of END_DATE found in the data -- [MAX] = When END_DATE exceeds GETDATE() the MAX value of END_DATE found in the data' AS VARCHAR(MAX)) AS COMMENT
FROM CTE_LOS_QA
)
SELECT QA_STATEMENT, [MEAS_VALUE_1], [MEAS_VALUE_2], REPLACE(PERC_TOTAL,' %','%') AS PERC_TOTAL, AVG_DIFFERENCE, [MIN], [MAX], COMMENT
FROM (
SELECT QA_STATEMENT, [MEAS_VALUE_1], [MEAS_VALUE_2], REPLACE(PERC_TOTAL,' %','%') AS PERC_TOTAL, AVG_DIFFERENCE, [MIN], [MAX], COMMENT
	, ROW_NUMBER() OVER (ORDER BY QA_STATEMENT ASC) R
FROM CTE_QA_STATEMENTS
)LOS
;


--TESTING
--SELECT * FROM QA.LENGTH_OF_STAY_VW


