/* ENACT QA view - QA_PATIENT_AGE
   v 0.1 - 20250331 - Darren W Henderson <darren.henderson@uky.edu>
   
   THIS VIEW MAY NEED ALTERATIONS AT YOUR SITE DEPENDING ON LOCAL DECISIONS ON THE STORAGE OF THE AGE AND AGE AT VISIT CONCEPTS
   THE DEFAULT VIEW WILL FOLLOW THE EN/ACT 4.1 ONTOLOGY AND PERFORM QA EVALUATIONS BASED ON THE EXPECTED LOCATIONS FOR THE AGE CONCEPTS
   
   The following QA measures are calculated:
   PTAGE0.0.1--PATIENT_DIMENSION.AGE_IN_YEARS_NUM is NULL
   PTAGE0.0.2--PATIENT_DIMENSION.AGE_IN_YEARS_NUM is not an INTEGER (DATATYPE CHECK DDL)
   PTAGE0.0.3--PATIENT_DIMENSION.AGE_IN_YEARS_NUM is not an INTEGER (LOGICAL CHECK)
   PTAGE0.0.4--PATIENT_DIMENSION.BIRTH_DATE is NULL
   PTAGE0.0.5--PATIENT_DIMENSION.BIRTH_DATE and PATIENT_DIMENSION.AGE_IN_YEARS_NUM disagree (C_DIMCODE STYLE AGE CALCULATION) - leverages QA.QA_ACT_V41_DEMOGRAPHICS built in 0.QA_ACT_V41_DEM-CalculatedFieldMetadata.sql
   PTAGE0.0.6--PATIENT_DIMENSION.BIRTH_DATE is future dated (> GETDATE())
   PTAGE0.0.7--PATIENT_DIMENSION.BIRTH_DATE is far in the past OR PATIENT_DIMENSION.AGE_IN_YEARS_NUM exceeds 120


*/

CREATE OR ALTER VIEW QA.PATIENT_AGE_VW AS
WITH CTE_PATIENT_AGE_QA AS (
SELECT BIRTH_DATE
	, AGE_IN_YEARS_NUM
FROM PATIENT_DIMENSION
)
, CTE_QA_STATEMENTS AS (
SELECT 'PTAGE0.0.1--PATIENT_DIMENSION.AGE_IN_YEARS_NUM is NULL - Incidents:' as QA_STATEMENT
	, SUM(CASE WHEN AGE_IN_YEARS_NUM IS NULL THEN 1 ELSE 0 END) AS [MEAS_VALUE_1]
	, COUNT(*) AS [MEAS_VALUE_2]
	, FORMAT(1.0*SUM(CASE WHEN AGE_IN_YEARS_NUM IS NULL THEN 1 ELSE 0 END)/COUNT(*),'P3') AS PERC_TOTAL
	, NULL AS AVG_DIFFERENCE -- N/A FOR THIS MEASURE
	, TRY_CAST(MIN(AGE_IN_YEARS_NUM) AS VARCHAR(100)) AS [MIN] -- VARCHAR(100) TO PREVENT ISSUES WITH DATE MIN/MAX UNION WITH BIRTH_DATE QA MEASURES
	, TRY_CAST(MAX(AGE_IN_YEARS_NUM) AS VARCHAR(100)) AS [MAX] -- VARCHAR(100) TO PREVENT ISSUES WITH DATE MIN/MAX UNION WITH BIRTH_DATE QA MEASURES
	, TRY_CAST('DEFINITION: [MEAS_VALUE_1] = Number of records where PATIENT_DIMENSION.AGE_IN_YEARS_NUM is NULL -- [MEAS_VALUE_2] = Number of records -- [PERC_TOTAL] = Percentage of PATIENT_DIMENSION affected -- [MIN] = Minimum AGE_IN_YEARS_NUM value in PATIENT_DIMENSION -- [MAX] = Maximum AGE_IN_YEARS_NUM value in PATIENT_DIMENSION' AS VARCHAR(MAX)) AS COMMENT
FROM CTE_PATIENT_AGE_QA
UNION ALL
SELECT 'PTAGE0.0.2--PATIENT_DIMENSION.AGE_IN_YEARS_NUM is not an INTEGER (DATATYPE CHECK DDL) - Boolean:' as QA_STATEMENT
	, CASE WHEN C.user_type_id NOT IN (48,52,56,127) THEN 0 ELSE 1 END AS [MEAS_VALUE_1]
	, NULL AS [MEAS_VALUE_2]
	, NULL AS PERC_TOTAL
	, NULL AS AVG_DIFFERENCE -- N/A FOR THIS MEASURE
	, NULL AS [MIN]
	, NULL AS [MAX]
	, TRY_CAST('DEFINITION: [MEAS_VALUE_1] = Boolean (1: True if PATIENT_DIMENSION.AGE_IN_YEARS_NUM is defined as one of the INTEGER datatypes in the table (TINYINT,SMALLINT,INT,BIGINT)) 0: False if PATIENT_DIMENSION.AGE_IN_YEARS_NUM is defined as a non-INTEGER datatype' AS VARCHAR(MAX)) AS COMMENT
FROM SYS.OBJECTS O
	JOIN SYS.COLUMNS C
		ON O.OBJECT_ID = C.OBJECT_ID
		AND O.OBJECT_ID = OBJECT_ID(N'PATIENT_DIMENSION')
		AND C.NAME = 'AGE_IN_YEARS_NUM'
UNION ALL
SELECT 'PTAGE0.0.3--PATIENT_DIMENSION.AGE_IN_YEARS_NUM is not an INTEGER (LOGICAL CHECK) - Incidents:' as QA_STATEMENT
	, SUM(CASE WHEN TRY_CAST(ISNULL(AGE_IN_YEARS_NUM,0) AS INT) IS NULL THEN 1 ELSE 0 END) AS [MEAS_VALUE_1] /*IGNORES NULL VALUES TO AVOID CONFLATING WITH PTAGE0.0.1*/
	, COUNT(*) AS [MEAS_VALUE_2]
	, FORMAT(1.0*SUM(CASE WHEN TRY_CAST(ISNULL(AGE_IN_YEARS_NUM,0) AS INT) IS NULL THEN 1 ELSE 0 END)/COUNT(*),'P3') AS PERC_TOTAL
	, NULL AS AVG_DIFFERENCE -- N/A FOR THIS MEASURE
	, NULL AS [MIN]
	, NULL AS [MAX]
	, TRY_CAST('DEFINITION: [MEAS_VALUE_1] = Number of records where casting AGE_IN_YEARS_NUM to an INTEGER fails. (Note this measure pairs with PTAGE0.0.2 when the datatype is not an INTEGER type) -- [MEAS_VALUE_2] = Number of records -- [PERC_TOTAL] = Percentage of PATIENT_DIMENSION affected' AS VARCHAR(MAX)) AS COMMENT
FROM CTE_PATIENT_AGE_QA
UNION ALL
SELECT 'PTAGE0.0.4--PATIENT_DIMENSION.BIRTH_DATE is NULL - Incidents:' as QA_STATEMENT
	, SUM(CASE WHEN BIRTH_DATE IS NULL THEN 1 ELSE 0 END) AS [MEAS_VALUE_1]
	, COUNT(*) AS [MEAS_VALUE_2]
	, FORMAT(1.0*SUM(CASE WHEN BIRTH_DATE IS NULL THEN 1 ELSE 0 END)/COUNT(*),'P3') AS PERC_TOTAL
	, NULL AS AVG_DIFFERENCE -- N/A FOR THIS MEASURE
	, TRY_CONVERT(VARCHAR(100), MIN(BIRTH_DATE), 23) AS [MIN] -- ISO8601 YYYY-MM-DD AS VARCHAR(100)
	, TRY_CONVERT(VARCHAR(100), MAX(BIRTH_DATE), 23) AS [MAX] -- ISO8601 YYYY-MM-DD AS VARCHAR(100)
	, TRY_CAST('DEFINITION: [MEAS_VALUE_1] = Number of records where PATIENT_DIMENSION.BIRTH_DATE is NULL -- [MEAS_VALUE_2] = Number of records -- [PERC_TOTAL] = Percentage of PATIENT_DIMENSION affected -- [MIN] = Minimum BIRTH_DATE value in PATIENT_DIMENSION -- [MAX] = Maximum BIRTH_DATE value in PATIENT_DIMENSION' AS VARCHAR(MAX)) AS COMMENT
FROM CTE_PATIENT_AGE_QA
UNION ALL
SELECT 'PTAGE0.0.5--PATIENT_DIMENSION.BIRTH_DATE and PATIENT_DIMENSION.AGE_IN_YEARS_NUM disagree (C_DIMCODE STYLE AGE CALCULATION) - Incidents:' as QA_STATEMENT
	, SUM(CASE WHEN PA.AGE_IN_YEARS_NUM != D.AGE_CODE_INT THEN 1 ELSE 0 END)AS [MEAS_VALUE_1]
	, COUNT(*) AS [MEAS_VALUE_2]
	, FORMAT(1.0*SUM(CASE WHEN PA.AGE_IN_YEARS_NUM != D.AGE_CODE_INT THEN 1 ELSE 0 END)/COUNT(*),'P3') AS PERC_TOTAL
	, NULL AS AVG_DIFFERENCE -- N/A FOR THIS MEASURE
	, TRY_CONVERT(VARCHAR(100), MIN(BIRTH_DATE), 23) AS [MIN] -- ISO8601 YYYY-MM-DD AS VARCHAR(100)
	, TRY_CONVERT(VARCHAR(100), MAX(BIRTH_DATE), 23) AS [MAX] -- ISO8601 YYYY-MM-DD AS VARCHAR(100)
	, TRY_CAST('DEFINITION: [MEAS_VALUE_1] = Number of records where PATIENT_DIMENSION.BIRTH_DATE and PATIENT_DIMENSION.AGE_IN_YEARS_NUM disagree by applying the same C_DIMCODE predicate between checks that the i2b2 query generator would to calculat age from BIRTH_DATE to compare it to the stored AGE_IN_YEARS_NUM -- [MEAS_VALUE_2] = Number of records where BIRTH_DATE can match the date range checks of the ACT_DEM_V41 ONTOLOGY FOR AGE -- [PERC_TOTAL] = Percentage of ontology matching PATIENT_DIMENSION affected -- [MIN] = Minimum BIRTH_DATE value in PATIENT_DIMENSION (affected by inner join to DEM ONTOLOGY IN THIS MEASURE) -- [MAX] = Maximum BIRTH_DATE value in PATIENT_DIMENSION (affected by inner join to DEM ONTOLOGY IN THIS MEASURE)' AS VARCHAR(MAX)) AS COMMENT
FROM CTE_PATIENT_AGE_QA PA
	JOIN QA.QA_ACT_V41_DEMOGRAPHICS D
		ON PA.BIRTH_DATE BETWEEN D.LEFT_DT_COMPARE AND D.RIGHT_DT_COMPARE
UNION ALL
SELECT 'PTAGE0.0.6--PATIENT_DIMENSION.BIRTH_DATE is future dated (> GETDATE()) - Incidents:' as QA_STATEMENT
	, SUM(CASE WHEN BIRTH_DATE > GETDATE() THEN 1 ELSE 0 END) AS [MEAS_VALUE_1]
	, COUNT(*) AS [MEAS_VALUE_2]
	, FORMAT(1.0*SUM(CASE WHEN BIRTH_DATE > GETDATE() THEN 1 ELSE 0 END)/COUNT(*),'P3') AS PERC_TOTAL
	, AVG(CASE WHEN BIRTH_DATE > GETDATE() THEN DATEDIFF(HH,GETDATE(),BIRTH_DATE) ELSE 0 END)/24 AS AVG_DIFFERENCE
	, TRY_CONVERT(VARCHAR(100), MIN(BIRTH_DATE), 23) AS [MIN] -- ISO8601 YYYY-MM-DD AS VARCHAR(100)
	, TRY_CONVERT(VARCHAR(100), MAX(BIRTH_DATE), 23) AS [MAX] -- ISO8601 YYYY-MM-DD AS VARCHAR(100)
	, TRY_CAST('DEFINITION: [MEAS_VALUE_1] = Number of records where PATIENT_DIMENSION.BIRTH_DATE is future dated (> GETDATE()) -- [MEAS_VALUE_2] = Number of records -- [PERC_TOTAL] = Percentage of PATIENT_DIMENSION affected -- [AVG_DIFFERENCE] = When BIRTH_DATE exceeds GETDATE() what is the average distance from today -- [MIN] = Minimum BIRTH_DATE value in PATIENT_DIMENSION -- [MAX] = Maximum BIRTH_DATE value in PATIENT_DIMENSION' AS VARCHAR(MAX)) AS COMMENT
FROM CTE_PATIENT_AGE_QA
UNION ALL
SELECT 'PTAGE0.0.7--PATIENT_DIMENSION.BIRTH_DATE is far in the past OR PATIENT_DIMENSION.AGE_IN_YEARS_NUM exceeds 120 - Incidents:' as QA_STATEMENT
	, SUM(CASE WHEN BIRTH_DATE < '19200101' OR AGE_IN_YEARS_NUM > 120 THEN 1 ELSE 0 END) AS [MEAS_VALUE_1] -- CHOICE OF 19200101 WAS ARBITRARY HERE 
	, COUNT(*) AS [MEAS_VALUE_2]
	, FORMAT(1.0*SUM(CASE WHEN BIRTH_DATE < '19200101' OR AGE_IN_YEARS_NUM > 120 THEN 1 ELSE 0 END)/COUNT(*),'P3') AS PERC_TOTAL
	, NULL AS AVG_DIFFERENCE -- N/A FOR THIS MEASURE
	, TRY_CONVERT(VARCHAR(100), MIN(BIRTH_DATE), 23) AS [MIN] -- ISO8601 YYYY-MM-DD AS VARCHAR(100)
	, TRY_CONVERT(VARCHAR(100), MAX(BIRTH_DATE), 23) AS [MAX] -- ISO8601 YYYY-MM-DD AS VARCHAR(100)
	, TRY_CAST('DEFINITION: [MEAS_VALUE_1] = Number of records where PATIENT_DIMENSION.BIRTH_DATE is NULL -- [MEAS_VALUE_2] = Number of records -- [PERC_TOTAL] = Percentage of PATIENT_DIMENSION affected -- [MIN] = Minimum BIRTH_DATE value in PATIENT_DIMENSION -- [MAX] = Maximum BIRTH_DATE value in PATIENT_DIMENSION' AS VARCHAR(MAX)) AS COMMENT
FROM CTE_PATIENT_AGE_QA
)
SELECT QA_STATEMENT, [MEAS_VALUE_1], [MEAS_VALUE_2], REPLACE(PERC_TOTAL,' %','%') AS PERC_TOTAL, AVG_DIFFERENCE, [MIN], [MAX], COMMENT
FROM (
SELECT QA_STATEMENT, [MEAS_VALUE_1], [MEAS_VALUE_2], REPLACE(PERC_TOTAL,' %','%') AS PERC_TOTAL, AVG_DIFFERENCE, [MIN], [MAX], COMMENT
	, ROW_NUMBER() OVER (ORDER BY QA_STATEMENT ASC) R
FROM CTE_QA_STATEMENTS
)PTAGE

--TESTING
--SELECT * FROM QA.PATIENT_AGE_VW

